-- =============================================
-- Script Template
-- =============================================
SET IDENTITY_INSERT [dbo].[Country] ON
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (1, N'AF', N'AFG', 4, N'Afeganistão')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (2, N'ZA', N'ZAF', 710, N'África do Sul')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (3, N'AX', N'ALA', 248, N'Åland, Ilhas')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (4, N'AL', N'ALB', 8, N'Albânia')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (5, N'DE', N'DEU', 276, N'Alemanha')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (6, N'AD', N'AND', 20, N'Andorra')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (7, N'AO', N'AGO', 24, N'Angola')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (8, N'AI', N'AIA', 660, N'Anguilla')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (9, N'AQ', N'ATA', 10, N'Antárctida')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (10, N'AG', N'ATG', 28, N'Antigua e Barbuda')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (11, N'AN', N'ANT', 530, N'Antilhas Holandesas')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (12, N'SA', N'SAU', 682, N'Arábia Saudita')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (13, N'DZ', N'DZA', 12, N'Argélia')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (14, N'AR', N'ARG', 32, N'Argentina')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (15, N'AM', N'ARM', 51, N'Arménia')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (16, N'AW', N'ABW', 533, N'Aruba')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (17, N'AU', N'AUS', 36, N'Austrália')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (18, N'AT', N'AUT', 40, N'Áustria')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (19, N'AZ', N'AZE', 31, N'Azerbeijão')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (20, N'BS', N'BHS', 44, N'Bahamas')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (21, N'BH', N'BHR', 48, N'Bahrain')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (22, N'BD', N'BGD', 50, N'Bangladesh')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (23, N'BB', N'BRB', 52, N'Barbados')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (24, N'BE', N'BEL', 56, N'Bélgica')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (25, N'BZ', N'BLZ', 84, N'Belize')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (26, N'BJ', N'BEN', 204, N'Benin')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (27, N'BM', N'BMU', 60, N'Bermuda')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (28, N'BY', N'BLR', 112, N'Bielo-Rússia')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (29, N'BO', N'BOL', 68, N'Bolívia')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (30, N'BA', N'BIH', 70, N'Bósnia-Herzegovina')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (31, N'BW', N'BWA', 72, N'Botswana')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (32, N'BV', N'BVT', 74, N'Bouvet, Ilha')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (33, N'BR', N'BRA', 76, N'Brasil')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (34, N'BN', N'BRN', 96, N'Brunei')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (35, N'BG', N'BGR', 100, N'Bulgária')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (36, N'BF', N'BFA', 854, N'Burkina Faso')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (37, N'BI', N'BDI', 108, N'Burundi')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (38, N'BT', N'BTN', 64, N'Butão')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (39, N'CV', N'CPV', 132, N'Cabo Verde')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (40, N'KH', N'KHM', 116, N'Cambodja')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (41, N'CM', N'CMR', 120, N'Camarões')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (42, N'CA', N'CAN', 124, N'Canadá')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (43, N'KY', N'CYM', 136, N'Cayman, Ilhas')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (44, N'KZ', N'KAZ', 398, N'Cazaquistão')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (45, N'CF', N'CAF', 140, N'Centro-africana, República')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (46, N'TD', N'TCD', 148, N'Chade')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (47, N'CZ', N'CZE', 203, N'Checa, República')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (48, N'CL', N'CHL', 152, N'Chile')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (49, N'CN', N'CHN', 156, N'China')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (50, N'CY', N'CYP', 196, N'Chipre')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (51, N'CX', N'CXR', 162, N'Christmas, Ilha')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (52, N'CC', N'CCK', 166, N'Cocos, Ilhas')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (53, N'CO', N'COL', 170, N'Colômbia')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (54, N'KM', N'COM', 174, N'Comores')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (55, N'CG', N'COG', 178, N'Congo, República do')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (56, N'CD', N'COD', 180, N'Congo, República Democrática do (antigo Zaire)')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (57, N'CK', N'COK', 184, N'Cook, Ilhas')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (58, N'KR', N'KOR', 410, N'Coreia do Sul')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (59, N'KP', N'PRK', 408, N'Coreia, República Democrática da (Coreia do Norte)')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (60, N'CI', N'CIV', 384, N'Costa do Marfim')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (61, N'CR', N'CRI', 188, N'Costa Rica')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (62, N'HR', N'HRV', 191, N'Croácia')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (63, N'CU', N'CUB', 192, N'Cuba')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (64, N'DK', N'DNK', 208, N'Dinamarca')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (65, N'DJ', N'DJI', 262, N'Djibouti')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (66, N'DM', N'DMA', 212, N'Dominica')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (67, N'DO', N'DOM', 214, N'Dominicana, República')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (68, N'EG', N'EGY', 818, N'Egipto')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (69, N'SV', N'SLV', 222, N'El Salvador')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (70, N'AE', N'ARE', 784, N'Emiratos Árabes Unidos')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (71, N'EC', N'ECU', 218, N'Equador')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (72, N'ER', N'ERI', 232, N'Eritreia')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (73, N'SK', N'SVK', 703, N'Eslováquia')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (74, N'SI', N'SVN', 705, N'Eslovénia')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (75, N'ES', N'ESP', 724, N'Espanha')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (76, N'US', N'USA', 840, N'Estados Unidos da América')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (77, N'EE', N'EST', 233, N'Estónia')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (78, N'ET', N'ETH', 231, N'Etiópia')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (79, N'FO', N'FRO', 234, N'Faroe, Ilhas')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (80, N'FJ', N'FJI', 242, N'Fiji')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (81, N'PH', N'PHL', 608, N'Filipinas')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (82, N'FI', N'FIN', 246, N'Finlândia')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (83, N'FR', N'FRA', 250, N'França')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (84, N'GA', N'GAB', 266, N'Gabão')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (85, N'GM', N'GMB', 270, N'Gâmbia')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (86, N'GH', N'GHA', 288, N'Gana')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (87, N'GE', N'GEO', 268, N'Geórgia')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (88, N'GS', N'SGS', 239, N'Geórgia do Sul e Sandwich do Sul, Ilhas')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (89, N'GI', N'GIB', 292, N'Gibraltar')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (90, N'GR', N'GRC', 300, N'Grécia')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (91, N'GD', N'GRD', 308, N'Grenada')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (92, N'GL', N'GRL', 304, N'Gronelândia')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (93, N'GP', N'GLP', 312, N'Guadeloupe')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (94, N'GU', N'GUM', 316, N'Guam')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (95, N'GT', N'GTM', 320, N'Guatemala')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (96, N'GG', N'GGY', 831, N'Guernsey')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (97, N'GY', N'GUY', 328, N'Guiana')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (98, N'GF', N'GUF', 254, N'Guiana Francesa')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (99, N'GW', N'GNB', 624, N'Guiné-Bissau')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (100, N'GN', N'GIN', 324, N'Guiné-Conacri')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (101, N'GQ', N'GNQ', 226, N'Guiné Equatorial')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (102, N'HT', N'HTI', 332, N'Haiti')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (103, N'HM', N'HMD', 334, N'Heard e Ilhas McDonald, Ilha')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (104, N'HN', N'HND', 340, N'Honduras')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (105, N'HK', N'HKG', 344, N'Hong Kong')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (106, N'HU', N'HUN', 348, N'Hungria')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (107, N'YE', N'YEM', 887, N'Iémen')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (108, N'IN', N'IND', 356, N'Índia')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (109, N'ID', N'IDN', 360, N'Indonésia')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (110, N'IQ', N'IRQ', 368, N'Iraque')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (111, N'IR', N'IRN', 364, N'Irão')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (112, N'IE', N'IRL', 372, N'Irlanda')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (113, N'IS', N'ISL', 352, N'Islândia')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (114, N'IL', N'ISR', 376, N'Israel')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (115, N'IT', N'ITA', 380, N'Itália')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (116, N'JM', N'JAM', 388, N'Jamaica')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (117, N'JP', N'JPN', 392, N'Japão')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (118, N'JE', N'JEY', 832, N'Jersey')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (119, N'JO', N'JOR', 400, N'Jordânia')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (120, N'KI', N'KIR', 296, N'Kiribati')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (121, N'KW', N'KWT', 414, N'Kuwait')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (122, N'LA', N'LAO', 418, N'Laos')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (123, N'LS', N'LSO', 426, N'Lesoto')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (124, N'LV', N'LVA', 428, N'Letónia')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (125, N'LB', N'LBN', 422, N'Líbano')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (126, N'LR', N'LBR', 430, N'Libéria')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (127, N'LY', N'LBY', 434, N'Líbia')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (128, N'LI', N'LIE', 438, N'Liechtenstein')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (129, N'LT', N'LTU', 440, N'Lituânia')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (130, N'LU', N'LUX', 442, N'Luxemburgo')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (131, N'MO', N'MAC', 446, N'Macau')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (132, N'MK', N'MKD', 807, N'Macedónia, República da')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (133, N'MG', N'MDG', 450, N'Madagáscar')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (134, N'MY', N'MYS', 458, N'Malásia')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (135, N'MW', N'MWI', 454, N'Malawi')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (136, N'MV', N'MDV', 462, N'Maldivas')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (137, N'ML', N'MLI', 466, N'Mali')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (138, N'MT', N'MLT', 470, N'Malta')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (139, N'FK', N'FLK', 238, N'Malvinas, Ilhas (Falkland)')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (140, N'IM', N'IMN', 833, N'Man, Ilha de')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (141, N'MP', N'MNP', 580, N'Marianas Setentrionais')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (142, N'MA', N'MAR', 504, N'Marrocos')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (143, N'MH', N'MHL', 584, N'Marshall, Ilhas')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (144, N'MQ', N'MTQ', 474, N'Martinica')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (145, N'MU', N'MUS', 480, N'Maurícia')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (146, N'MR', N'MRT', 478, N'Mauritânia')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (147, N'YT', N'MYT', 175, N'Mayotte')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (148, N'UM', N'UMI', 581, N'Menores Distantes dos Estados Unidos, Ilhas')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (149, N'MX', N'MEX', 484, N'México')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (150, N'MM', N'MMR', 104, N'Myanmar (antiga Birmânia)')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (151, N'FM', N'FSM', 583, N'Micronésia, Estados Federados da')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (152, N'MZ', N'MOZ', 508, N'Moçambique')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (153, N'MD', N'MDA', 498, N'Moldávia')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (154, N'MC', N'MCO', 492, N'Mónaco')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (155, N'MN', N'MNG', 496, N'Mongólia')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (156, N'ME', N'MNE', 499, N'Montenegro')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (157, N'MS', N'MSR', 500, N'Montserrat')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (158, N'NA', N'NAM', 516, N'Namíbia')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (159, N'NR', N'NRU', 520, N'Nauru')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (160, N'NP', N'NPL', 524, N'Nepal')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (161, N'NI', N'NIC', 558, N'Nicarágua')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (162, N'NE', N'NER', 562, N'Níger')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (163, N'NG', N'NGA', 566, N'Nigéria')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (164, N'NU', N'NIU', 570, N'Niue')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (165, N'NF', N'NFK', 574, N'Norfolk, Ilha')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (166, N'NO', N'NOR', 578, N'Noruega')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (167, N'NC', N'NCL', 540, N'Nova Caledónia')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (168, N'NZ', N'NZL', 554, N'Nova Zelândia (Aotearoa)')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (169, N'OM', N'OMN', 512, N'Oman')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (170, N'NL', N'NLD', 528, N'Países Baixos (Holanda)')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (171, N'PW', N'PLW', 585, N'Palau')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (172, N'PS', N'PSE', 275, N'Palestina')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (173, N'PA', N'PAN', 591, N'Panamá')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (174, N'PG', N'PNG', 598, N'Papua-Nova Guiné')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (175, N'PK', N'PAK', 586, N'Paquistão')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (176, N'PY', N'PRY', 600, N'Paraguai')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (177, N'PE', N'PER', 604, N'Peru')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (178, N'PN', N'PCN', 612, N'Pitcairn')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (179, N'PF', N'PYF', 258, N'Polinésia Francesa')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (180, N'PL', N'POL', 616, N'Polónia')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (181, N'PR', N'PRI', 630, N'Porto Rico')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (182, N'PT', N'PRT', 620, N'Portugal')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (183, N'QA', N'QAT', 634, N'Qatar')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (184, N'KE', N'KEN', 404, N'Quénia')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (185, N'KG', N'KGZ', 417, N'Quirguistão')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (186, N'GB', N'GBR', 826, N'Reino Unido da Grã-Bretanha e Irlanda do Norte')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (187, N'RE', N'REU', 638, N'Reunião')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (188, N'RO', N'ROU', 642, N'Roménia')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (189, N'RW', N'RWA', 646, N'Ruanda')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (190, N'RU', N'RUS', 643, N'Rússia')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (191, N'EH', N'ESH', 732, N'Saara Ocidental')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (192, N'AS', N'ASM', 16, N'Samoa Americana')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (193, N'WS', N'WSM', 882, N'Samoa (Samoa Ocidental)')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (194, N'PM', N'SPM', 666, N'Saint Pierre et Miquelon')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (195, N'SB', N'SLB', 90, N'Salomão, Ilhas')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (196, N'KN', N'KNA', 659, N'São Cristóvão e Névis (Saint Kitts e Nevis)')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (197, N'SM', N'SMR', 674, N'San Marino')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (198, N'ST', N'STP', 678, N'São Tomé e Príncipe')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (199, N'VC', N'VCT', 670, N'São Vicente e Granadinas')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (200, N'SH', N'SHN', 654, N'Santa Helena')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (201, N'LC', N'LCA', 662, N'Santa Lúcia')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (202, N'SN', N'SEN', 686, N'Senegal')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (203, N'SL', N'SLE', 694, N'Serra Leoa')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (204, N'RS', N'SRB', 688, N'Sérvia')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (205, N'SC', N'SYC', 690, N'Seychelles')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (206, N'SG', N'SGP', 702, N'Singapura')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (207, N'SY', N'SYR', 760, N'Síria')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (208, N'SO', N'SOM', 706, N'Somália')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (209, N'LK', N'LKA', 144, N'Sri Lanka')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (210, N'SZ', N'SWZ', 748, N'Suazilândia')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (211, N'SD', N'SDN', 736, N'Sudão')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (212, N'SE', N'SWE', 752, N'Suécia')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (213, N'CH', N'CHE', 756, N'Suíça')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (214, N'SR', N'SUR', 740, N'Suriname')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (215, N'SJ', N'SJM', 744, N'Svalbard e Jan Mayen')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (216, N'TH', N'THA', 764, N'Tailândia')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (217, N'TW', N'TWN', 158, N'Taiwan')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (218, N'TJ', N'TJK', 762, N'Tajiquistão')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (219, N'TZ', N'TZA', 834, N'Tanzânia')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (220, N'TF', N'ATF', 260, N'Terras Austrais e Antárticas Francesas (TAAF)')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (221, N'IO', N'IOT', 86, N'Território Britânico do Oceano Índico')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (222, N'TL', N'TLS', 626, N'Timor-Leste')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (223, N'TG', N'TGO', 768, N'Togo')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (224, N'TK', N'TKL', 772, N'Toquelau')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (225, N'TO', N'TON', 776, N'Tonga')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (226, N'TT', N'TTO', 780, N'Trindade e Tobago')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (227, N'TN', N'TUN', 788, N'Tunísia')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (228, N'TC', N'TCA', 796, N'Turks e Caicos')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (229, N'TM', N'TKM', 795, N'Turquemenistão')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (230, N'TR', N'TUR', 792, N'Turquia')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (231, N'TV', N'TUV', 798, N'Tuvalu')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (232, N'UA', N'UKR', 804, N'Ucrânia')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (233, N'UG', N'UGA', 800, N'Uganda')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (234, N'UY', N'URY', 858, N'Uruguai')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (235, N'UZ', N'UZB', 860, N'Usbequistão')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (236, N'VU', N'VUT', 548, N'Vanuatu')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (237, N'VA', N'VAT', 336, N'Vaticano')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (238, N'VE', N'VEN', 862, N'Venezuela')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (239, N'VN', N'VNM', 704, N'Vietname')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (240, N'VI', N'VIR', 850, N'Virgens Americanas, Ilhas')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (241, N'VG', N'VGB', 92, N'Virgens Britânicas, Ilhas')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (242, N'WF', N'WLF', 876, N'Wallis e Futuna')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (243, N'ZM', N'ZMB', 894, N'Zâmbia')
INSERT [dbo].[Country] ([ID], [ISO], [ISO3], [NumCode], [Description]) VALUES (244, N'ZW', N'ZWE', 716, N'Zimbabwe')
SET IDENTITY_INSERT [dbo].[Country] OFF
