SET IDENTITY_INSERT [dbo].[Church] ON
INSERT [dbo].[Church] ([ID], [Name], [Local], [Priest], [Foundation], [Status], [Parish_id], [Address_id])
VALUES (1, N'BASÍLICA DE NOSSA SENHORA DO CARMO', N'', N'', null, 1, null, null)
INSERT [dbo].[Church] ([ID], [Name], [Local], [Priest], [Foundation], [Status], [Parish_id], [Address_id])
VALUES (2, N'CAPELA DA CASA MARISTELLA', N'', N'', null, 1, null, null)
INSERT [dbo].[Church] ([ID], [Name], [Local], [Priest], [Foundation], [Status], [Parish_id], [Address_id])
VALUES (3, N'CAPELA DA JAQUEIRA', N'', N'', NULL, 1, null, null)
INSERT [dbo].[Church] ([ID], [Name], [Local], [Priest], [Foundation], [Status], [Parish_id], [Address_id])
VALUES (4, N'CAPELA DAS MERCEDÁRIAS', N'', N'', null, 1, null, null)
INSERT [dbo].[Church] ([ID], [Name], [Local], [Priest], [Foundation], [Status], [Parish_id], [Address_id])
VALUES (5, N'CAPELA DO MENINO JESUS', N'', N'', NULL, 1, null, null)
INSERT [dbo].[Church] ([ID], [Name], [Local], [Priest], [Foundation], [Status], [Parish_id], [Address_id])
VALUES (6, N'CAPELA NOSSA SENHORA DA SAÚDE', N'', N'Pe. Sílvio Milanez', null, 1, null, null)
INSERT [dbo].[Church] ([ID], [Name], [Local], [Priest], [Foundation], [Status], [Parish_id], [Address_id])
VALUES (7, N'CAPELA NOSSA SENHORA DAS GRAÇAS (ALTO DO MANDU)', N'', N'Pe. Moisés', null, 1, null, null)
INSERT [dbo].[Church] ([ID], [Name], [Local], [Priest], [Foundation], [Status], [Parish_id], [Address_id])
VALUES (8, N'CAPELA NOSSA SENHORA DAS GRAÇAS (SÍTIO DOS PINTOS)', N'', N'Pe. Moisés', null, 1, null, null)
INSERT [dbo].[Church] ([ID], [Name], [Local], [Priest], [Foundation], [Status], [Parish_id], [Address_id])
VALUES (9, N'CAPELA NOSSA SENHORA DE FÁTIMA (ALTO DO DEODATO)', N'', N'Pe. Paulo Sérgio Monteiro Nunes', null, 1, null, null)
INSERT [dbo].[Church] ([ID], [Name], [Local], [Priest], [Foundation], [Status], [Parish_id], [Address_id])
VALUES (10, N'CAPELA NOSSA SENHORA DE LOURDES (CASA AMARELA)', N'', N'Pe. Moisés', null, 1, null, null)
INSERT [dbo].[Church] ([ID], [Name], [Local], [Priest], [Foundation], [Status], [Parish_id], [Address_id])
VALUES (11, N'CAPELA SANTA CECÍLIA', N'', N'Pe. Cícero Ferreira de Paula', null, 1, null, null)
INSERT [dbo].[Church] ([ID], [Name], [Local], [Priest], [Foundation], [Status], [Parish_id], [Address_id])
VALUES (12, N'CAPELA SANTA TERESINHA', N'', N'', null, 1, null, null)
INSERT [dbo].[Church] ([ID], [Name], [Local], [Priest], [Foundation], [Status], [Parish_id], [Address_id])
VALUES (13, N'CAPELA SANTO AMARO DAS SALINAS', N'', N'Fr. Marconi Lins de Araújo, OFM', null, 1, null, null)
INSERT [dbo].[Church] ([ID], [Name], [Local], [Priest], [Foundation], [Status], [Parish_id], [Address_id])
VALUES (14, N'CAPELA SÃO BRÁS (DOIS IRMÃOS)', N'', N'Pe. Moisés', null, 1, null, null)
INSERT [dbo].[Church] ([ID], [Name], [Local], [Priest], [Foundation], [Status], [Parish_id], [Address_id])
VALUES (15, N'CAPELA SÃO FRANCISCO (TORRE)', N'', N'', NULL, 1, null, null)
INSERT [dbo].[Church] ([ID], [Name], [Local], [Priest], [Foundation], [Status], [Parish_id], [Address_id])
VALUES (16, N'CAPELA SÃO JOÃO BATISTA (ALTO DO CÉU)', N'', N'Pe. Paulo Sérgio Monteiro Nunes', null, 1, null, null)
INSERT [dbo].[Church] ([ID], [Name], [Local], [Priest], [Foundation], [Status], [Parish_id], [Address_id])
VALUES (17, N'CAPELA SÃO JOSÉ DOS MANGUINHOS', N'', N'Capelão: Pe. Luciano José Rodrigues Brito', null, 1, null, null)
INSERT [dbo].[Church] ([ID], [Name], [Local], [Priest], [Foundation], [Status], [Parish_id], [Address_id])
VALUES (18, N'CAPELA SÃO PEDRO (CÓRREGO DA FORTUNA)', N'', N'Pe. Moisés', null, 1, null, null)
INSERT [dbo].[Church] ([ID], [Name], [Local], [Priest], [Foundation], [Status], [Parish_id], [Address_id])
VALUES (19, N'CASA PROVINCIAL NOSSA SENHORA DAS GRAÇAS', N'Paróquia Nossa Senhora da Soledade', N'fronteiras', null, 1, null, null)
INSERT [dbo].[Church] ([ID], [Name], [Local], [Priest], [Foundation], [Status], [Parish_id], [Address_id])
VALUES (20, N'COLÉGIO DAMAS', N'', N'Capelão: Mons. Moacyr da Costa Pinto', null, 1, null, null)
INSERT [dbo].[Church] ([ID], [Name], [Local], [Priest], [Foundation], [Status], [Parish_id], [Address_id])
VALUES (21, N'COLÉGIO NÓBREGA', N'', N'', NULL, 1, null, null)
INSERT [dbo].[Church] ([ID], [Name], [Local], [Priest], [Foundation], [Status], [Parish_id], [Address_id])
VALUES (22, N'COLÉGIO NOSSA SENHORA AUXILIADORA', N'', N'', null, 1, null, null)
INSERT [dbo].[Church] ([ID], [Name], [Local], [Priest], [Foundation], [Status], [Parish_id], [Address_id])
VALUES (23, N'COLÉGIO NOSSA SENHORA DE LOURDES', N'', N'', NULL, 1, null, null)
INSERT [dbo].[Church] ([ID], [Name], [Local], [Priest], [Foundation], [Status], [Parish_id], [Address_id])
VALUES (24, N'COLÉGIO ROSA GATTORNO', N'', N'', null, 1, null, null)
INSERT [dbo].[Church] ([ID], [Name], [Local], [Priest], [Foundation], [Status], [Parish_id], [Address_id])
VALUES (25, N'COLÉGIO SALESIANO', N'', N'', null, 1, null, null)
INSERT [dbo].[Church] ([ID], [Name], [Local], [Priest], [Foundation], [Status], [Parish_id], [Address_id])
VALUES (26, N'COLÉGIO SANTA CATARINA', N'', N'', null, 1, null, null)
INSERT [dbo].[Church] ([ID], [Name], [Local], [Priest], [Foundation], [Status], [Parish_id], [Address_id])
VALUES (27, N'COLÉGIO SÃO LUÍS', N'', N'', NULL, 1, null, null)
INSERT [dbo].[Church] ([ID], [Name], [Local], [Priest], [Foundation], [Status], [Parish_id], [Address_id])
VALUES (28, N'COLÉGIO VERA CRUZ', N'', N'', NULL, 1, null, null)
INSERT [dbo].[Church] ([ID], [Name], [Local], [Priest], [Foundation], [Status], [Parish_id], [Address_id])
VALUES (29, N'COLÉGIO VIRGEM PODEROSA', N'', N'', NULL, 1, null, null)
INSERT [dbo].[Church] ([ID], [Name], [Local], [Priest], [Foundation], [Status], [Parish_id], [Address_id])
VALUES (30, N'CONCATEDRAL SÃO PEDRO DOS CLÉRIGOS', N'', N'', null, 1, null, null)
INSERT [dbo].[Church] ([ID], [Name], [Local], [Priest], [Foundation], [Status], [Parish_id], [Address_id])
VALUES (31, N'CONVENTO DE SANTO ANTÔNIO', N'', N'', NULL, 1, null, null)
INSERT [dbo].[Church] ([ID], [Name], [Local], [Priest], [Foundation], [Status], [Parish_id], [Address_id])
VALUES (32, N'CONVENTO DE SÃO FÉLIX CANTALICE (PINA)', N'', N'', null, 1, null, null)
INSERT [dbo].[Church] ([ID], [Name], [Local], [Priest], [Foundation], [Status], [Parish_id], [Address_id])
VALUES (33, N'HOSPITAL PORTUGUÊS', N'', N'', NULL, 1, null, null)
INSERT [dbo].[Church] ([ID], [Name], [Local], [Priest], [Foundation], [Status], [Parish_id], [Address_id])
VALUES (34, N'HOSPITAL SANTO AMARO', N'', N'', null, 1, null, null)
INSERT [dbo].[Church] ([ID], [Name], [Local], [Priest], [Foundation], [Status], [Parish_id], [Address_id])
VALUES (35, N'IGREJA DA MADRE DE DEUS', N'', N'Pe. Roberto Nogueira do Nascimento', null, 1, null, null)
INSERT [dbo].[Church] ([ID], [Name], [Local], [Priest], [Foundation], [Status], [Parish_id], [Address_id])
VALUES (36, N'IGREJA DA ORDEM TERCEIRA DE SÃO FRANCISCO', N'', N'', NULL, 1, null, null)
INSERT [dbo].[Church] ([ID], [Name], [Local], [Priest], [Foundation], [Status], [Parish_id], [Address_id])
VALUES (37, N'IGREJA DE SANTA TERESA - ORDEM TERCEIRA DO CARMO', N'', N'', NULL, 1, null, null)
INSERT [dbo].[Church] ([ID], [Name], [Local], [Priest], [Foundation], [Status], [Parish_id], [Address_id])
VALUES (38, N'IGREJA DA SANTA CRUZ', N'', N'Pe. Cícero Ferreira de Paula', null, 1, null, null)
INSERT [dbo].[Church] ([ID], [Name], [Local], [Priest], [Foundation], [Status], [Parish_id], [Address_id])
VALUES (39, N'IGREJA DE NOSSA SENHORA DA CONCEIÇÃO DOS MILITARES', N'', N'', NULL, 1, null, null)
INSERT [dbo].[Church] ([ID], [Name], [Local], [Priest], [Foundation], [Status], [Parish_id], [Address_id])
VALUES (40, N'IGREJA DE NOSSA SENHORA DE FÁTIMA (BOA VIAGEM)', N'', N'Pe. João Bosco Costa Lima', null, 1, null, null)
INSERT [dbo].[Church] ([ID], [Name], [Local], [Priest], [Foundation], [Status], [Parish_id], [Address_id])
VALUES (41, N'IGREJA DE NOSSA SENHORA DE PIEDADE', N'', N'', NULL, 1, null, null)
INSERT [dbo].[Church] ([ID], [Name], [Local], [Priest], [Foundation], [Status], [Parish_id], [Address_id])
VALUES (42, N'IGREJA DE NOSSA SENHORA DO LIVRAMENTO', N'', N'', NULL, 1, null, null)
INSERT [dbo].[Church] ([ID], [Name], [Local], [Priest], [Foundation], [Status], [Parish_id], [Address_id])
VALUES (43, N'IGREJA DE NOSSA SENHORA DO ROSÁRIO (BOA VIAGEM)', N'', N'Pe. Adriano', null, 1, null, null)
INSERT [dbo].[Church] ([ID], [Name], [Local], [Priest], [Foundation], [Status], [Parish_id], [Address_id])
VALUES (44, N'IGREJA DE NOSSA SENHORA DO ROSÁRIO DA BOA VISTA', N'', N'Pe. Cícero Ferreira de Paula', null, 1, null, null)
INSERT [dbo].[Church] ([ID], [Name], [Local], [Priest], [Foundation], [Status], [Parish_id], [Address_id])
VALUES (45, N'IGREJA DE NOSSA SENHORA DO ROSÁRIO DOS PRETOS', N'', N'Pe. Roberto Nogueira do Nascimento', null, 1, null ,null)
INSERT [dbo].[Church] ([ID], [Name], [Local], [Priest], [Foundation], [Status], [Parish_id], [Address_id])
VALUES (46, N'IGREJA DE NOSSA SENHORA DOS AFLITOS', N'', N'', NULL, 1, null, null)
INSERT [dbo].[Church] ([ID], [Name], [Local], [Priest], [Foundation], [Status], [Parish_id], [Address_id])
VALUES (47, N'IGREJA DE SANTA ISABEL', N'', N'Pe. Paulo Sérgio Monteiro Nunes', null, 1, null, null)
INSERT [dbo].[Church] ([ID], [Name], [Local], [Priest], [Foundation], [Status], [Parish_id], [Address_id])
VALUES (48, N'IGREJA DE SANTA LUZIA (ESTÂNCIA)', N'', N'Pe. José Lins de Moura', null, 1, null, null)
INSERT [dbo].[Church] ([ID], [Name], [Local], [Priest], [Foundation], [Status], [Parish_id], [Address_id])
VALUES (49, N'IGREJA DE SANTO ANTÔNIO (ÁGUA FRIA)', N'', N'Pe. João Carlos Santana da Costa', null, 1, null, null)
INSERT [dbo].[Church] ([ID], [Name], [Local], [Priest], [Foundation], [Status], [Parish_id], [Address_id])
VALUES (50, N'IGREJA DE SÃO GONÇALO', N'', N'Pe. Cícero Ferreira de Paula', null, 1, null, null)
INSERT [dbo].[Church] ([ID], [Name], [Local], [Priest], [Foundation], [Status], [Parish_id], [Address_id])
VALUES (51, N'IGREJA DE SÃO SEBASTIÃO (AV. NORTE)', N'', N'Fr. João Sannig, OFM', null, 1, null, null)
INSERT [dbo].[Church] ([ID], [Name], [Local], [Priest], [Foundation], [Status], [Parish_id], [Address_id])
VALUES (52, N'IGREJA DO BOM JESUS (CASA AMARELA)', N'', N'Pe. Carlos Frederico Soares', null, 1, null, null)
INSERT [dbo].[Church] ([ID], [Name], [Local], [Priest], [Foundation], [Status], [Parish_id], [Address_id])
VALUES (53, N'IGREJA DO CORAÇÃO IMACULADO DE MARIA - BRASÍLIA TEIMOSA', N'', N'Frei Aluísio Domingos de Barro, OFM', null, 1, null, null)
INSERT [dbo].[Church] ([ID], [Name], [Local], [Priest], [Foundation], [Status], [Parish_id], [Address_id])
VALUES (54, N'IGREJA DO CRISTO REDENTOR (JORDÃO ALTO)', N'', N'Pe. Antônio Pereira, OMI', null, 1, null, null)
INSERT [dbo].[Church] ([ID], [Name], [Local], [Priest], [Foundation], [Status], [Parish_id], [Address_id])
VALUES (55, N'IGREJA DO ESPÍRITO SANTO', N'Paróquia do Santíssimo Sacramento', N'', NULL, 1, null, null)
INSERT [dbo].[Church] ([ID], [Name], [Local], [Priest], [Foundation], [Status], [Parish_id], [Address_id])
VALUES (56, N'IGREJA DO MORRO DA CONCEIÇÃO', N'Paróquia Nossa Senhora da Conceição', N'Pe. José Josivan Bezerra de Sales', null, 1, null, null)
INSERT [dbo].[Church] ([ID], [Name], [Local], [Priest], [Foundation], [Status], [Parish_id], [Address_id])
VALUES (57, N'IGREJA DO TERÇO', N'Paróquia Desconhecida', N'', NULL, 1, null, null)
INSERT [dbo].[Church] ([ID], [Name], [Local], [Priest], [Foundation], [Status], [Parish_id], [Address_id])
VALUES (58, N'IGREJA MATRIZ DA BOA VISTA', N'Paróquia do Santíssimo Sacramento', N'Pe. Cícero Ferreira de Paula', null, 1, null, null)
INSERT [dbo].[Church] ([ID], [Name], [Local], [Priest], [Foundation], [Status], [Parish_id], [Address_id])
VALUES (59, N'IGREJA MATRIZ DA IMBIRIBEIRA', N'Paróquia de São Sebastião e São Cristóvão', N'Pe. Nildo Leal de Sá', null, 1, null, null)
INSERT [dbo].[Church] ([ID], [Name], [Local], [Priest], [Foundation], [Status], [Parish_id], [Address_id])
VALUES (60, N'IGREJA MATRIZ DA LUZ', N'Paróquia de Nossa Senhora da Luz', N'Pe. Hector Miguel Ruiz', null, 1, null, null)
INSERT [dbo].[Church] ([ID], [Name], [Local], [Priest], [Foundation], [Status], [Parish_id], [Address_id])
VALUES (61, N'IGREJA MATRIZ DA MACAXEIRA', N'Paróquia Santa Maria (Macaxeira)', N'Pe. João Crisóstomo Custódio.', null, 1, null, null)
INSERT [dbo].[Church] ([ID], [Name], [Local], [Priest], [Foundation], [Status], [Parish_id], [Address_id])
VALUES (62, N'IGREJA MATRIZ DA MADALENA (PERPÉTUO SOCORRO)', N'Paróquia Nossa Senhora do Perpétuo Socorro', N'Pe. Gerson Aparecido dos Santos, CSSR', null, 1, null, null)
INSERT [dbo].[Church] ([ID], [Name], [Local], [Priest], [Foundation], [Status], [Parish_id], [Address_id])
VALUES (63, N'IGREJA MATRIZ DA MANGABEIRA', N'Paróquia Nossa Senhora de Fátima (Mangabeira)', N'Pe. Gilberto José do Nascimento', null, 1, null, null)
INSERT [dbo].[Church] ([ID], [Name], [Local], [Priest], [Foundation], [Status], [Parish_id], [Address_id])
VALUES (64, N'IGREJA MATRIZ DA MANGUEIRA', N'Paróquia Nossa Senhora da Conceição', N'Pe. Josias Barbosa da Silva', null, 1, null, null)
INSERT [dbo].[Church] ([ID], [Name], [Local], [Priest], [Foundation], [Status], [Parish_id], [Address_id])
VALUES (65, N'IGREJA MATRIZ DA MUSTARDINHA', N'Paróquia Nossa Senhora do Rosário de Pompéia', N'Pe. João Carlos Magalhães Silva, SCJ', null, 1, null, null)
INSERT [dbo].[Church] ([ID], [Name], [Local], [Priest], [Foundation], [Status], [Parish_id], [Address_id])
VALUES (66, N'IGREJA MATRIZ DA PENHA', N'Paróquia Nossa Senhora da Penha', N'Fr. Luís de França Fernandes, OfmCap', null, 1, null, null)
INSERT [dbo].[Church] ([ID], [Name], [Local], [Priest], [Foundation], [Status], [Parish_id], [Address_id])
VALUES (67, N'IGREJA MATRIZ DA SOLEDADE', N'Paróquia Nossa Senhora da Soledade', N'Pe. Nilson Lourenço da Silva', null, 1, null, null)
INSERT [dbo].[Church] ([ID], [Name], [Local], [Priest], [Foundation], [Status], [Parish_id], [Address_id])
VALUES (68, N'IGREJA MATRIZ DA TORRE', N'Paróquia Nossa Senhora do Rosário', N'Mons. Romeu Gusmão da Fonte', null, 1, null, null)
INSERT [dbo].[Church] ([ID], [Name], [Local], [Priest], [Foundation], [Status], [Parish_id], [Address_id])
VALUES (69, N'IGREJA MATRIZ DA VÁRZEA', N'Paróquia Nossa Senhora do Rosário (Várzea)', N'Pe. Geraldo Van Geel, SCJ', null, 1, null, null)
INSERT [dbo].[Church] ([ID], [Name], [Local], [Priest], [Foundation], [Status], [Parish_id], [Address_id])
VALUES (70, N'IGREJA MATRIZ DAS GRAÇAS', N'Paróquia Nossa Senhora das Graças', N'Pe. João Oliveira Novais', null, 1, null, null)
INSERT [dbo].[Church] ([ID], [Name], [Local], [Priest], [Foundation], [Status], [Parish_id], [Address_id])
VALUES (71, N'IGREJA MATRIZ DE APIPUCOS', N'Paróquia Nossa Senhora das Dores', N'Pe. Moisés Ferreira de Lima', null, 1, null, null)
INSERT [dbo].[Church] ([ID], [Name], [Local], [Priest], [Foundation], [Status], [Parish_id], [Address_id])
VALUES (72, N'IGREJA MATRIZ DE BEBERIBE', N'Paróquia Nossa Senhora da Conceição', N'Pe. Maurício Florêncio de Lima', null, 1, null, null)
INSERT [dbo].[Church] ([ID], [Name], [Local], [Priest], [Foundation], [Status], [Parish_id], [Address_id])
VALUES (73, N'IGREJA MATRIZ DE BELÉM', N'Paróquia Nossa Senhora Belém', N'Pe. Augusto César Figueiroa de Arruda', null, 1, null, null)
INSERT [dbo].[Church] ([ID], [Name], [Local], [Priest], [Foundation], [Status], [Parish_id], [Address_id])
VALUES (74, N'IGREJA MATRIZ DE BOA VIAGEM (PRACINHA)', N'Paróquia Nossa Senhora da Boa Viagem', N'Mons. Edvaldo Bezerra da Silva', null, 1, null, null)
INSERT [dbo].[Church] ([ID], [Name], [Local], [Priest], [Foundation], [Status], [Parish_id], [Address_id])
VALUES (75, N'IGREJA MATRIZ DE CAMPO GRANDE', N'Paróquia Nossa Senhora do Bom Parto', N'Pe. José Roberto da Silva França', null, 1, null, null)
INSERT [dbo].[Church] ([ID], [Name], [Local], [Priest], [Foundation], [Status], [Parish_id], [Address_id])
VALUES (76, N'IGREJA MATRIZ DE CASA FORTE', N'Paróquia do Sagrado Coração de Jesus', N'Cônego José Edvaldo Gomes', null, 1, null, null)
INSERT [dbo].[Church] ([ID], [Name], [Local], [Priest], [Foundation], [Status], [Parish_id], [Address_id])
VALUES (77, N'IGREJA MATRIZ DE JARDIM SÃO PAULO', N'Paróquia São Paulo Apóstolo', N'Pe. Luciano José Rodrigues Brito', null, 1, null, null)
INSERT [dbo].[Church] ([ID], [Name], [Local], [Priest], [Foundation], [Status], [Parish_id], [Address_id])
VALUES (78, N'IGREJA MATRIZ DE NOVA DESCOBERTA', N'Paróquia Nossa Senhora de Lourdes', N'Pe. Marcelo José da Silva', null, 1, null, null)
INSERT [dbo].[Church] ([ID], [Name], [Local], [Priest], [Foundation], [Status], [Parish_id], [Address_id])
VALUES (79, N'IGREJA MATRIZ DE SANTO ANTÔNIO', N'Paróquia do Santíssimo Sacramento', N'Pe. Roberto Nogueira do Nascimento', null, 1, null, null)
INSERT [dbo].[Church] ([ID], [Name], [Local], [Priest], [Foundation], [Status], [Parish_id], [Address_id])
VALUES (80, N'IGREJA MATRIZ DE SÃO JOSÉ', N'Paróquia São José', N'Pe. José Augusto Rodrigues Esteves', null, 1, null, null)
INSERT [dbo].[Church] ([ID], [Name], [Local], [Priest], [Foundation], [Status], [Parish_id], [Address_id])
VALUES (81, N'IGREJA MATRIZ DE SÃO LOURENÇO DA MATA', N'Paróquia de São Lourenço Mártir', N'Pe. Hector Miguel Ruiz', null, 1, null, null)
INSERT [dbo].[Church] ([ID], [Name], [Local], [Priest], [Foundation], [Status], [Parish_id], [Address_id])
VALUES (82, N'IGREJA MATRIZ DE TEJIPIÓ', N'Paróquia Nossa Senhora do Rosário (Tejipió)', N'Pe. Sérgio Pereira da Silva', null, 1, null, null)
INSERT [dbo].[Church] ([ID], [Name], [Local], [Priest], [Foundation], [Status], [Parish_id], [Address_id])
VALUES (83, N'IGREJA MATRIZ DO ALTO DO PASCOAL', N'Paróquia São Sebastião (Alto do Pascoal)', N'Pe. Paulo Sérgio Monteiro Nunes', null, 1, null, null)
INSERT [dbo].[Church] ([ID], [Name], [Local], [Priest], [Foundation], [Status], [Parish_id], [Address_id])
VALUES (84, N'IGREJA MATRIZ DO BARRO', N'Paróquia Nossa Senhora da Conceição', N'Pe. Domingos de Sá Filho, MSF', null, 1, null, null)
INSERT [dbo].[Church] ([ID], [Name], [Local], [Priest], [Foundation], [Status], [Parish_id], [Address_id])
VALUES (85, N'IGREJA MATRIZ DO BONGI', N'Paróquia São João Bosco', N'Pe. Francisco Cibin, SDB', null, 1, null, null)
INSERT [dbo].[Church] ([ID], [Name], [Local], [Priest], [Foundation], [Status], [Parish_id], [Address_id])
VALUES (86, N'IGREJA MATRIZ DO CAJUEIRO', N'Paróquia São Judas Tadeu', N'Pe. Roberto Nogueira do Nascimento', null, 1, null, null)
INSERT [dbo].[Church] ([ID], [Name], [Local], [Priest], [Foundation], [Status], [Parish_id], [Address_id])
VALUES (87, N'IGREJA MATRIZ DO CORDEIRO', N'Paróquia São Sebastião (Cordeiro)', N'Pe. Oscar Martins Fonseca', null, 1, null, null)
INSERT [dbo].[Church] ([ID], [Name], [Local], [Priest], [Foundation], [Status], [Parish_id], [Address_id])
VALUES (88, N'IGREJA MATRIZ DO ENGENHO DO MEIO', N'Paróquia Nossa Senhora das Graças (Engenho do Meio)', N'Pe. José Erinaldo Ferreira de Lima', null, 1, null, null)
INSERT [dbo].[Church] ([ID], [Name], [Local], [Priest], [Foundation], [Status], [Parish_id], [Address_id])
VALUES (89, N'IGREJA MATRIZ DO ESPINHEIRO', N'Paróquia do Coração Eucarístico de Jesus', N'Frei Geraldo de Araújo Lima, O.Carm', null, 1, null, null)
INSERT [dbo].[Church] ([ID], [Name], [Local], [Priest], [Foundation], [Status], [Parish_id], [Address_id])
VALUES (90, N'IGREJA MATRIZ DO IBURA', N'Paróquia Nossa Senhora de Fátima (Ibura)', N'Fr. Aluísio Domingos de Barros, OFM', null, 1, null, null)
INSERT [dbo].[Church] ([ID], [Name], [Local], [Priest], [Foundation], [Status], [Parish_id], [Address_id])
VALUES (91, N'IGREJA MATRIZ DO IPSEP', N'Paróquia Nossa Senhora da Conceição Aparecida', N'Pe. Paulo Sales Costa', null, 1, null, null)
INSERT [dbo].[Church] ([ID], [Name], [Local], [Priest], [Foundation], [Status], [Parish_id], [Address_id])
VALUES (92, N'IGREJA MATRIZ DO IPUTINGA', N'Paróquia Nossa Senhora da Conceição', N'Pe. Adilson José Ferreira da Silva', null, 1, null, null)
INSERT [dbo].[Church] ([ID], [Name], [Local], [Priest], [Foundation], [Status], [Parish_id], [Address_id])
VALUES (93, N'IGREJA MATRIZ DO LARGO DA PAZ', N'Paróquia Nossa Senhora da Paz', N'Pe. Fábio Paz de Queiroz', null, 1, null, null)
INSERT [dbo].[Church] ([ID], [Name], [Local], [Priest], [Foundation], [Status], [Parish_id], [Address_id])
VALUES (94, N'IGREJA MATRIZ DO PINA', N'Paróquia Nossa Senhora do Rosário (Pina)', N'Fr. Paulo Sérgio Bezerra Silva, OFMCap', null, 1, null, null)
INSERT [dbo].[Church] ([ID], [Name], [Local], [Priest], [Foundation], [Status], [Parish_id], [Address_id])
VALUES (95, N'IGREJA MATRIZ DO SANCHO', N'Paróquia São João Batista', N'Pe. Heribert Stahl, MSF e Pe. Paulo César Costa dos Santos, MSF', null, 1, null, null)
INSERT [dbo].[Church] ([ID], [Name], [Local], [Priest], [Foundation], [Status], [Parish_id], [Address_id])
VALUES (96, N'IGREJA MATRIZ DO VASCO DA GAMA', N'Paróquia São Sebastião (Vasco de Gama)', N'Pe. Amaurílio Machado de Souza, SDB', null, 1, null, null)
INSERT [dbo].[Church] ([ID], [Name], [Local], [Priest], [Foundation], [Status], [Parish_id], [Address_id])
VALUES (97, N'IGREJA MATRIZ DOS REMÉDIOS', N'Paróquia Nossa Senhora dos Remédios', N'Pe. Cosmo Francisco do Nascimento', null, 1, null, null)
INSERT [dbo].[Church] ([ID], [Name], [Local], [Priest], [Foundation], [Status], [Parish_id], [Address_id])
VALUES (98, N'INSTITUTO NOSSA SENHORA DE FÁTIMA', N'Paróquia Nossa Senhora da Soledade', N'institutonsfatima', null, 1, null, null)
INSERT [dbo].[Church] ([ID], [Name], [Local], [Priest], [Foundation], [Status], [Parish_id], [Address_id])
VALUES (99, N'UNIVERSIDADE CATÓLICA', N'Paróquia Nossa Senhora da Soledade', N'unicap', null, 1, null, null)
SET IDENTITY_INSERT [dbo].[Church] OFF
