CREATE TABLE [dbo].[MassTime] (
    [Id]         INT      IDENTITY (1, 1) NOT NULL,
    [Status]     BIT      NOT NULL,
    [Time]       DATETIME NOT NULL,
    [Church_id]  INT      NULL,
    [Weekday_id] INT      NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF),
	CONSTRAINT FK_MASSTIME_CHURCH FOREIGN KEY ([Church_id]) REFERENCES [dbo].[Church] ([Id]) ON DELETE NO ACTION ON UPDATE NO ACTION,
	CONSTRAINT FK_MASSTIME_WEEKDAY FOREIGN KEY ([Weekday_id]) REFERENCES [dbo].[Weekday] ([Id]) ON DELETE NO ACTION ON UPDATE NO ACTION
);

