-- @MASSTIMES = '08:30.1;18:00.1;18:30.3;18:30.4;18:30.5;18:30.6;18:00.7'

CREATE OR ALTER PROCEDURE INSERT_MASSTIMES
(
    @CHURCH_ID INT,
    @MASSTIMES VARCHAR(MAX)
)
AS
BEGIN

    SET NOCOUNT ON

    INSERT INTO [dbo].[MassTime]([Status],[Time],[Church_id],[Weekday_id])
    SELECT 1, PARSENAME(value, 2), @CHURCH_ID, PARSENAME(value,1)
	FROM STRING_SPLIT(@MASSTIMES, ';')

END
GO
